server:
  port: 1234
  servlet:
    context-path: /
spring:
  application:
    name: istio-gateway
  cloud:
    polaris:
      namespace: default # 配置注册命名空间
      address: grpc://192.168.160.100:8091
      discovery:
        enabled: true
      stat:
        enabled: true
        port: 28082
route:
  user:
    url: 127.0.0.1:1235